import os, sys


def main():
  if len(sys.argv) != 2:
    print >> sys.stderr, "Usage: %s <graph>" % sys.argv[0]
  
  tmp = os.tmpnam() + '.dot'
  try:
    with open(tmp, 'w') as out:
      with open(sys.argv[1]) as f:
        print >> out, 'graph "%s" {'
        for line in f:
          line = line.strip()
          fromNode, toNode = line[:3], line[3:]
          print >> out, "%s -- %s;" % (fromNode, toNode)
        print >> out, '}'

    pdfname = os.path.basename(os.path.splitext(sys.argv[1])[0] + '.pdf')
    dotcmd = '/usr/bin/dot -Tpdf -o%s %s' % (pdfname, tmp)
    print "pdf will be called", pdfname
    print "pdf will be generated by:", dotcmd
    ret = os.system(dotcmd)
    print "return code was", ret
  finally:
    if os.path.exists(tmp):
      os.remove(tmp)


if __name__ == '__main__':
  main()

